[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-arch-blackout2
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=arch-blackout2
GtkTheme=arch-blackout2
IconTheme=arch-blackout2
MetacityTheme=arch-blackout2
