# Shell variables
# Generated by 'wal'
wallpaper='/home/jll/.wallpaper/Ou3Oksx.jpg'

# Special
background='#121022'
foreground='#f8f8f2'
cursor='#f8f8f2'

# Colors
color0='#121022'
color1='#DA0098'
color2='#E51CB6'
color3='#CD3ABE'
color4='#BD93F9'
color5='#AF1CC8'
color6='#8822E4'
color7='#f8f8f2'
color8='#9e5f97'
color9='#DA0098'
color10='#E51CB6'
color11='#CD3ABE'
color12='#BD93F9'
color13='#AF1CC8'
color14='#8822E4'
color15='#f8f8f2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
