--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jll/.config/wpg/wallpapers/astronaut-colorful-ship-4k_1540749986.jpg"

-- Special
background="#0A0807"
foreground="#f7f7f7"
cursor="#f7f7f7"

-- Colors
color0="#0A0807"
color1="#E90F58"
color2="#C05648"
color3="#73863B"
color4="#F85CBE"
color5="#E6A759"
color6="#E2DE66"
color7="#f7f7f7"
color8="#a06b87"
color9="#E90F58"
color10="#C05648"
color11="#73863B"
color12="#F85CBE"
color13="#E6A759"
color14="#E2DE66"
color15="#f7f7f7"
