# Shell variables
# Generated by 'wal'
wallpaper='/home/jll/.wallpaper/astronaut-colorful-ship-4k_1540749986.jpg'

# Special
background='#0A0807'
foreground='#f7f7f7'
cursor='#f7f7f7'

# Colors
color0='#0A0807'
color1='#E90F58'
color2='#C05648'
color3='#73863B'
color4='#F85C8E'
color5='#E6A759'
color6='#E2DE66'
color7='#f7f7f7'
color8='#a06b87'
color9='#E90F58'
color10='#C05648'
color11='#73863B'
color12='#F85C8E'
color13='#E6A759'
color14='#E2DE66'
color15='#f7f7f7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
