--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/jll/.wallpaper/Ou3Oksx.jpg"

-- Special
background="#121022"
foreground="#f8f8f2"
cursor="#f8f8f2"

-- Colors
color0="#121022"
color1="#DA0098"
color2="#E51CB6"
color3="#CD3ABE"
color4="#BD93F9"
color5="#AF1CC8"
color6="#8822E4"
color7="#f8f8f2"
color8="#9e5f97"
color9="#DA0098"
color10="#E51CB6"
color11="#CD3ABE"
color12="#BD93F9"
color13="#AF1CC8"
color14="#8822E4"
color15="#f8f8f2"
