#! /bin/sh
# 01100010 01110011 01110000 01110111 01101101 #
#      _       _       _       _       _       #
#    _( )__  _( )__  _( )__  _( )__  _( )__    #
#  _|     __|     __|     __|     __|     _|   #
# (_ B _ ((_ S _ ((_ P _ ((_ W _ ((_ M _ (_    #
#   |_( )__||_( )__||_( )__||_( )__||_( )__|   #
#                                              #
# 01100010 01110011 01110000 01110111 01101101 #
# Define workspaces
bspc monitor -d        '1' '2' '3' '4' '5' '6' '7' '8'
# Borders
bspc config border_width                2 
bspc config normal_border_color         "#1F292E"
bspc config focused_border_color        "#EC222F"
bspc config presel_feedback_color       "#EC222F"
# Gaps & padding
bspc config window_gap                  0
bspc config top_padding                 21 
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
# State/layout settings
bspc config single_monocle              true
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config split_ratio                 .539
bspc wm --adopt-orphans
# Pointer/focus
bspc config pointer_follows_monitor     true
bspc config focus_follows_pointer       true
bspc config click_to_focus              false
bspc config pointer_modifier            mod1
bspc config pointer_action1             move
bspc config pointer_action2             resize_corner
# Window rules
bspc rule -a Nitrogen                   state=floating
bspc rule -a Skype                      state=floating
bspc rule -a Whatsie                    state=floating
bspc rule -a Pavucontrol                state=floating
bspc rule -a Grsync                     state=floating
bspc rule -a GParted                    state=floating
bspc rule -a Gnome-disks                state=floating
bspc rule -a Gnome-calculator           state=floating
bspc rule -a File-roller                state=floating
bspc rule -a Python3                    state=floating
bspc rule -a Gufw.py                    state=floating
bspc rule -a Gnome-terminal             state=floating
bspc rule -a Chromium                   state=floating
bspc rule -a Gsimplecal                 manage=off
# Set key binds
sxhkd &
# Launch status bar
bspwm-bar &
