#!/bin/sh
VOL=$(pamixer --get-volume-human | tr -d '%')
if [ "$VOL" = "muted" ] || [ "$VOL" -eq 0 ]; then
    printf "mute🔇 "
         elif [ "$VOL" -gt 0 ] && [ "$VOL" -le 33 ]; then
             printf "%s%%🔈 " "$VOL"
         elif [ "$VOL" -gt 33 ] && [ "$VOL" -le 66 ]; then
             printf "%s%%🔉 " "$VOL"
         else
             printf "%s%%🔊 " "$VOL"
         fi
